name: ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check .
      - name: Tests
        run: |
          pytest -q

  docker-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push API image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/pdm-api:${{ github.sha }}
          docker build -f infra/docker/Dockerfile.api -t $IMAGE .
          docker push $IMAGE
      - name: Build and push Worker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/pdm-worker:${{ github.sha }}
          docker build -f infra/docker/Dockerfile.worker -t $IMAGE .
          docker push $IMAGE


